---
- name: Install epel-release
  become: yes
  yum:
    name: epel-release
    state: present

- name: Install pip
  become: yes
  yum:
    name: python-pip
    state: present

- name: Install python shade
  become: yes
  pip:
    name: shade
    state: present

- name: Install libselinux-python
  become: yes
  yum:
    name: libselinux-python
    state: present

- name: Make sure openstack config directory exists
  file: path="~/.config/openstack" state=directory

- name: Copy clouds.yml configuration to remote server
  copy:
    src: clouds.yml
    dest: "~/.config/openstack/clouds.yml"