[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  name = "github.com/kubevirt/device-plugin-manager"
  branch = "master"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  branch = "master"
