#[[constraint]]
#  name = "github.com/openshift/generic-admission-server"
#  version = "1.10"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

#[[constraint]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.10.0"

#[[constraint]]
#  name = "k8s.io/client-go"
#  version = "7.0.0"
