---
- name: Configure local networks on hosts
  hosts:
    - node
  gather_facts: no
  roles:
    - networks/roles/create-local-networks

- name: Configure simple networking
  hosts:
    - master
  gather_facts: no
  roles:
    - networks/roles/prepare-os-host
    - networks/roles/create-networks
